# Creating Tensors in PyTorch
- From the book ML with Pytorch

In [1]:
import torch
import numpy as np

In [2]:
np.set_printoptions(precision=3)

#### Tensor Properties
retained their properties from their source

In [3]:
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype=np.int32)
ta = torch.tensor(a)
tb = torch.from_numpy(b)
print(ta)
print(tb)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


#### Tensor of Ones

In [7]:
t_ones = torch.ones(2, 3)
print(t_ones)
t_ones.shape

tensor([[1., 1., 1.],
        [1., 1., 1.]])


torch.Size([2, 3])

#### Random Tensors

In [8]:
rand_t = torch.rand(2, 3)
print(rand_t)

tensor([[0.5861, 0.1400, 0.2886],
        [0.3380, 0.7557, 0.7275]])


#### Manipulating the data type and shape of a tensor
- See pytorch tensor attributes for all other dtypes

In [9]:
ta_new = ta.to(torch.int64)
print(ta_new)
print(ta_new.dtype)

tensor([1, 2, 3])
torch.int64


#### Transpose

In [11]:
t = torch.rand(3, 5)
t

tensor([[0.7635, 0.2540, 0.7599, 0.4772, 0.6747],
        [0.2158, 0.5964, 0.9429, 0.3509, 0.8510],
        [0.4919, 0.6567, 0.8292, 0.5469, 0.5738]])

In [12]:
t_tr = torch.transpose(t, 0, 1)
t_tr

tensor([[0.7635, 0.2158, 0.4919],
        [0.2540, 0.5964, 0.6567],
        [0.7599, 0.9429, 0.8292],
        [0.4772, 0.3509, 0.5469],
        [0.6747, 0.8510, 0.5738]])

#### Reshape

In [13]:
t = torch.zeros(30)
t

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.])

In [14]:
t_reshape = t.reshape(5, 6)
t_reshape

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

#### Remove unnecessary dimensions

In [15]:
t = torch.zeros(1, 2, 1, 4, 1)
t

tensor([[[[[0.],
           [0.],
           [0.],
           [0.]]],


         [[[0.],
           [0.],
           [0.],
           [0.]]]]])

In [17]:
t_sqz = torch.squeeze(t, 2)
t_sqz

tensor([[[[0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.]]]])

In [18]:
print(t.shape, '--->' , t_sqz.shape)

torch.Size([1, 2, 1, 4, 1]) ---> torch.Size([1, 2, 4, 1])


#### Mathematical Operations

In [19]:
# Initiating 2 tensors 
torch.manual_seed(1)
t1 = 2 * torch.rand(5, 2) - 1
t2 = torch.normal(mean=0, std=1, size=(5,2))
t1, t2

(tensor([[ 0.5153, -0.4414],
         [-0.1939,  0.4694],
         [-0.9414,  0.5997],
         [-0.2057,  0.5087],
         [ 0.1390, -0.1224]]),
 tensor([[ 0.8590,  0.7056],
         [-0.3406, -1.2720],
         [-1.1948,  0.0250],
         [-0.7627,  1.3969],
         [-0.3245,  0.2879]]))

In [20]:
# Multiply elementwise
t3 = torch.multiply(t1, t2)
t3

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])

In [21]:
# Mean of each column
t4 = torch.mean(t1, axis=0)
t4

tensor([-0.1373,  0.2028])

In [23]:
# Calc mean of each row
t45 = torch.mean(t1, axis=1)
t45

tensor([ 0.0369,  0.1378, -0.1709,  0.1515,  0.0083])

#### Matrix multiplication

In [24]:
t5 = torch.matmul(t1, torch.transpose(t2, 0, 1))
t5

tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])

In [35]:
t6 = torch.tensor([[2, 2, 2],
                   [3, 3, 3]])
t7 = torch.tensor([[1, 2],
                   [2, 3],
                   [3, 4]])
torch.matmul(t6, t7)

tensor([[12, 18],
        [18, 27]])

#### Split

In [41]:
torch.chunk(t7, 3)

(tensor([[1, 2]]), tensor([[2, 3]]), tensor([[3, 4]]))

#### Concat

In [54]:
# 1D
torch.cat([torch.tensor([1,2,3]), torch.tensor([3,2,1])], axis=0)

tensor([1, 2, 3, 3, 2, 1])

In [56]:
# 2D
torch.cat([t6, torch.transpose(t7, 0, 1)], axis=0)

tensor([[2, 2, 2],
        [3, 3, 3],
        [1, 2, 3],
        [2, 3, 4]])

### Datasets

#### DataLoader

In [57]:
# pg 378

#### Dataset
- From scratch

In [58]:
torch.manual_seed(1)
tx = torch.rand([4, 3], dtype=torch.float32)
ty = torch.arange(4)
tx, ty

(tensor([[0.7576, 0.2793, 0.4031],
         [0.7347, 0.0293, 0.7999],
         [0.3971, 0.7544, 0.5695],
         [0.4388, 0.6387, 0.5247]]),
 tensor([0, 1, 2, 3]))

In [61]:
# to create a joint dataset from two tensors (from scratch)
from torch.utils.data import Dataset
class JointDataset(Dataset):
    def __init__(self, x, y): # This is where the initial logic happens
        self.x = x
        self.y = y
        
    def __len__(self): 
        return len(self.x)
    
    def __getitem__(self, idx): # Returns the corresponding sample to the given index
        return self.x[idx], self.y[idx]

In [67]:
jd = JointDataset(tx, ty)
for example in jd:
    print(' x: ', example[0], ' y: ', example[1])

 x:  tensor([0.7576, 0.2793, 0.4031])  y:  tensor(0)
 x:  tensor([0.7347, 0.0293, 0.7999])  y:  tensor(1)
 x:  tensor([0.3971, 0.7544, 0.5695])  y:  tensor(2)
 x:  tensor([0.4388, 0.6387, 0.5247])  y:  tensor(3)


#### Datasets
- From pytorch library

In [62]:
from torch.utils.data import TensorDataset
joint_dataset = TensorDataset(tx, ty)

In [64]:
for example in joint_dataset:
    print(' x: ', example[0], ' y: ', example[1])

 x:  tensor([0.7576, 0.2793, 0.4031])  y:  tensor(0)
 x:  tensor([0.7347, 0.0293, 0.7999])  y:  tensor(1)
 x:  tensor([0.3971, 0.7544, 0.5695])  y:  tensor(2)
 x:  tensor([0.4388, 0.6387, 0.5247])  y:  tensor(3)
