# Creating Tensors in PyTorch
- From the book ML with Pytorch

In [1]:
import torch
import numpy as np

In [2]:
np.set_printoptions(precision=3)

#### Tensor Properties
retained their properties from their source

In [3]:
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype=np.int32)
ta = torch.tensor(a)
tb = torch.from_numpy(b)
print(ta)
print(tb)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


#### Tensor of Ones

In [7]:
t_ones = torch.ones(2, 3)
print(t_ones)
t_ones.shape

tensor([[1., 1., 1.],
        [1., 1., 1.]])


torch.Size([2, 3])

#### Random Tensors

In [8]:
rand_t = torch.rand(2, 3)
print(rand_t)

tensor([[0.5861, 0.1400, 0.2886],
        [0.3380, 0.7557, 0.7275]])


#### Manipulating the data type and shape of a tensor
- See pytorch tensor attributes for all other dtypes

In [9]:
ta_new = ta.to(torch.int64)
print(ta_new)
print(ta_new.dtype)

tensor([1, 2, 3])
torch.int64
